# security/config/yamllint.yaml
extends: default

rules:
  truthy:
    level: error
  comments:
    min-spaces-from-content: 1
  document-start:
    level: error
  line-length:
    max: 120
    level: warning
  trailing-spaces: enable
  indentation:
    spaces: 2
    indent-sequences: consistent
  new-line-at-end-of-file: enable
  empty-lines:
    max: 2
