- name: Создать namespace health-api
  shell: k3s kubectl create namespace health-api || true
  changed_when: false

- name: Проверка — namespace health-api существует
  shell: k3s kubectl get namespace health-api -o name
  register: ns_check
  changed_when: false
  failed_when: ns_check.rc != 0 or 'namespace/health-api' not in ns_check.stdout
