# Baseline под Python, Dockerfile и K8s YAML.

rules:
  # --- Python: опасные вызовы ---
  - id: python-eval-exec
    message: Избегай eval()/exec(); используй безопасные альтернативы.
    severity: ERROR
    languages: [python]
    pattern-either:
      - pattern: eval($X)
      - pattern: exec($X)

  - id: python-subprocess-shell-true
    message: subprocess с shell=True уязвим для инъекций. Используй список аргументов и shell=False.
    severity: ERROR
    languages: [python]
    pattern-either:
      - pattern: subprocess.Popen(..., shell=True, ...)
      - pattern: subprocess.run(..., shell=True, ...)
      - pattern: subprocess.call(..., shell=True, ...)
      - pattern: os.system($CMD)

  - id: python-pyyaml-unsafe-load
    message: yaml.load без SafeLoader небезопасен. Используй yaml.safe_load / SafeLoader.
    severity: ERROR
    languages: [python]
    patterns:
      - pattern: yaml.load($X)
      - pattern-not: yaml.load($X, Loader=yaml.SafeLoader)
      - pattern-not: yaml.safe_load($X)

  - id: python-requests-verify-false
    message: Отключена проверка TLS (verify=False) в requests.
    severity: WARNING
    languages: [python]
    pattern-either:
      - pattern: requests.get(..., verify=False, ...)
      - pattern: requests.post(..., verify=False, ...)
      - pattern: requests.put(..., verify=False, ...)
      - pattern: requests.delete(..., verify=False, ...)
      - pattern: requests.patch(..., verify=False, ...)
      - pattern: requests.head(..., verify=False, ...)

  # --- Generic: хардкоды секретов ---
  - id: generic-hardcoded-secret
    message: Похоже на хардкод секрета/пароля/токена.
    severity: WARNING
    languages: [generic]
    pattern-regex: (?i)\b(pass(word)?|secret|token|api[_-]?key|access[_-]?key)\b\s*[:=]\s*['"][^'"]{8,}['"]

  # --- Dockerfile ---
  - id: docker-latest-tag
    message: Не фиксирован тег образа (latest). Используй иммутабельный тег/дижест.
    severity: WARNING
    languages: [dockerfile]
    pattern: |
      FROM $IMAGE:latest

  - id: docker-user-root
    message: Контейнер запускается от root. Задай USER с непривилегированным UID.
    severity: WARNING
    languages: [dockerfile]
    pattern: |
      USER root

  # --- Kubernetes YAML ---
  - id: k8s-privileged-true
    message: securityContext.privileged: true
    severity: ERROR
    languages: [yaml]
    patterns:
      - pattern: |
          spec:
            ...
            containers:
              ...
              - ...
                securityContext:
                  privileged: true

  - id: k8s-run-as-root
    message: Разрешен запуск от root. Укажи runAsNonRoot: true и uid.
    severity: ERROR
    languages: [yaml]
    patterns:
      - pattern: |
          spec:
            ...
            containers:
              ...
              - ...
                securityContext:
                  runAsNonRoot: false
      - pattern: |
          spec:
            ...
            containers:
              ...
              - ...
                securityContext:
                  runAsUser: 0

  - id: k8s-missing-requests-limits
    message: Не заданы resources.requests/limits.
    severity: WARNING
    languages: [yaml]
    pattern-either:
      - pattern: |
          spec:
            ...
            containers:
              ...
              - ...
                resources:
                  limits: {}
      - pattern: |
          spec:
            ...
            containers:
              ...
              - ...
                resources:
                  requests: {}
      - pattern: |
          spec:
            ...
            containers:
              ...
              - ...
                resources: null
      - pattern: |
          spec:
            ...
            containers:
              ...
              - ...
        metavariable-pattern:
          metavariable: $X
          pattern-not: |
            resources:
              requests:
                cpu: $CPU
                memory: $MEM
              limits:
                cpu: $LCPU
                memory: $LMEM

  - id: k8s-host-namespaces
    message: Включены hostPID/hostIPC/hostNetwork — избегай.
    severity: WARNING
    languages: [yaml]
    pattern-either:
      - pattern: |
          spec:
            hostPID: true
      - pattern: |
          spec:
            hostIPC: true
      - pattern: |
          spec:
            hostNetwork: true
