services:
  health-api-1:
    build:
      context: ../your-local-health-api-path
    volumes:
      - ../your-local-health-api-path:/app
    command: python app.py
    ports:
      - "8081:8080"
    environment:
      SERVICE_NAME: ${SERVICE_NAME}
      VERSION: ${VERSION}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      JAEGER_AGENT_HOST: ${JAEGER_AGENT_HOST}
      JAEGER_AGENT_PORT: ${JAEGER_AGENT_PORT}
    networks:
      - internal

networks:
  internal:
    name: ${SERVICE_NAME}_internal
    driver: bridge
