services:
  health-api-1:
    image: ghcr.io/vik-devops-lab/health-api-backend:${BACKEND_TAG:-v${VERSION}}
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    environment:
      SERVICE_NAME: ${SERVICE_NAME}
      VERSION: ${VERSION}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      JAEGER_SERVICE_NAME: ${SERVICE_NAME}
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 15s
    depends_on:
      - pgbouncer
      - kafka
    networks:
      - internal

  health-api-2:
    image: ghcr.io/vik-devops-lab/health-api-backend:${BACKEND_TAG:-v${VERSION}}
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    environment:
      SERVICE_NAME: ${SERVICE_NAME}
      VERSION: ${VERSION}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      JAEGER_SERVICE_NAME: ${SERVICE_NAME}
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 15s
    depends_on:
      - pgbouncer
      - kafka
    networks:
      - internal

  health-api-frontend:
    image: ghcr.io/vik-devops-lab/health-api-frontend:${BACKEND_TAG:-v${VERSION}}
    restart: unless-stopped
    volumes:
      - shared-ui:/usr/share/nginx/html/ui
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost/ui/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - health-api-1
      - health-api-2
    networks:
      - internal

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - shared-ui:/usr/share/nginx/html/ui
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      - health-api-1
      - health-api-2
      - jaeger
      - grafana
      - redpanda-console
    networks:
      - internal

volumes:
  shared-ui:

networks:
  internal:
    name: ${SERVICE_NAME}_internal
    driver: bridge
