- name: Ждать освобождения apt lock
  become: true
  shell: |
    for i in {1..60}; do
      fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 || exit 0
      sleep 2
    done
    exit 1
  args:
    executable: /bin/bash
  register: apt_lock
  failed_when: apt_lock.rc != 0
  changed_when: false

- name: Установить Docker
  apt:
    name: docker.io
    update_cache: yes
    state: present

- name: Проверка - docker установлен и работает
  shell: docker info >/dev/null 2>&1
  register: docker_check
  changed_when: false
  failed_when: docker_check.rc != 0

- name: Добавить пользователя ubuntu в группу docker
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Проверка - ubuntu записан в группу docker
  shell: grep '^docker:' /etc/group | grep -q '\bubuntu\b'
  register: docker_group_check
  changed_when: false
  failed_when: docker_group_check.rc != 0
